Canary Automated Testing  (#471)
## Summary

This updates the Push To Canary workflow to push the updated jars and
wheel to the cloud canaries and run integration tests.

The jobs are as follows:
* **build_artifacts** 
builds the jars and wheel from the main branch and uploads them to
github for use in separate jobs simultaneously
* **push_to_aws**
downloads the jars and wheel from github and uploads them to the s3
zipline-artifacts-canary bucket under version "candidate"
* **push_to_gcp**
downloads the jars and wheel from github and uploads them to the gcs
zipline-artifacts-canary bucket under version "candidate"
* **run_aws_integration_tests**
runs the quickstart compile and backfill based on
[scripts/distribution/run_aws_quickstart.sh](https://github.com/zipline-ai/chronon/blob/main/scripts/distribution/run_aws_quickstart.sh)
* **run_gcp_integration_tests**
runs the quickstart compile, backfill, group-by-upload, upload-to-kv,
metadata-upload, and fetch based on
[scripts/distribution/run_gcp_quickstart.sh](https://github.com/zipline-ai/chronon/blob/main/scripts/distribution/run_gcp_quickstart.sh)
* **clean_up_artifacts**
removes the jars and wheel from github to minimize the storage costs.
* **merge_to_main-passing-tests**
if the tests all pass, this will merge the latest commits to the branch
"main-passing-tests". This also creates a txt file artifact marking
which commit sha passed which is saved by github.
* **on_fail_notify_slack**
if the tests fail, this will send a notification to the
"integration-tests" channel of our Slack.

A test run of the workflow can be seen here:
https://github.com/zipline-ai/chronon/actions/runs/13913346353

## Checklist
- [ ] Added Unit Tests
- [ ] Covered by existing CI
- [x] Integration tested
- [ ] Documentation update



<!-- This is an auto-generated comment: release notes by coderabbit.ai
-->
## Summary by CodeRabbit

## Summary by CodeRabbit

- **Chores**
- Enhanced our release pipeline to streamline package generation and
distribution.
	- Automated deployment of new build packages across AWS and GCP.
	- Introduced cleanup routines to optimize the post-deployment process.
- Updated job structure for improved artifact management and deployment.
- Added new jobs for building artifacts and uploading them to cloud
storage, including `build_artifacts`, `push_to_aws`, `push_to_gcp`, and
`clean_up_artifacts`.
	- Defined outputs for generated artifacts to improve tracking.
- Improved flexibility in deployment scripts for different environments
(dev and canary).
- Updated scripts to conditionally handle resource management based on
environment settings.
- Introduced environment-specific configurations for AWS and GCP
operations.
	- Added integration testing jobs for AWS and GCP post-deployment.
- Enhanced scripts for AWS and GCP to support environment-specific
operations and configurations.
- Introduced a mechanism to switch between different environments
affecting resource management and command configurations.
<!-- end of auto-generated comment: release notes by coderabbit.ai -->

diff --git a/.github/workflows/push_to_canary.yaml b/.github/workflows/push_to_canary.yaml
--- a/.github/workflows/push_to_canary.yaml
+++ b/.github/workflows/push_to_canary.yaml
@@ -3,7 +3,7 @@ name: Push To Canary
 on:
   push:
     branches:
-      - 'main'
+      - main
 
 concurrency:
   group: ${{ github.workflow }}-${{ github.ref }}
@@ -11,24 +11,19 @@ concurrency:
 
 env:
   AWS_ACCOUNT_ID: ${{secrets.AWS_ACCOUNT_ID}}
-  AWS_QUICKSTART_REPOSITORY: zipline-ai/canary-quickstart
   AWS_REGION: ${{secrets.AWS_REGION}}
   GCP_PROJECT_ID: ${{secrets.GCP_PROJECT_ID}}
   GCP_REGION: ${{secrets.GCP_REGION}}
 
 jobs:
-  push_to_cloud:
+  build_artifacts:
     runs-on: ubuntu-latest
 
     permissions:
-      id-token: write
       contents: read
 
     steps:
       - uses: actions/checkout@v4
-
-      - name: Set up QEMU
-        uses: docker/setup-qemu-action@v3
 
       - name: Setup JDK
         uses: actions/setup-java@v4
@@ -54,6 +49,46 @@ jobs:
           cd .. && \
           sudo rm -rf thrift-${{env.THRIFT_VERSION}} thrift-${{env.THRIFT_VERSION}}.tar.gz
 
+      - name: Set up Python
+        uses: actions/setup-python@v5
+        with:
+          python-version: '3.11' # This should match the version used in [chronon]/.toolversions
+
+      - name: Get the latest release tag
+        id: get_tag
+        run: |
+          git fetch --tags
+          TAG=$(git tag --sort=-creatordate | head -n 1)
+          TAG="${TAG#v}"
+          echo "Latest release tag: $TAG"
+
+          echo "tag=$TAG" >> $GITHUB_OUTPUT
+
+      - name: Build Python Wheel
+        id: build-wheel
+        shell: bash
+        env:
+          VERSION: "${{ steps.get_tag.outputs.tag }}+${{ github.sha }}"
+        run: |
+          set -eo pipefail
+          echo "Building wheel"
+          python3 -m pip install --upgrade pip
+          python3 -m pip install --upgrade setuptools wheel
+          
+          ./scripts/distribution/build_wheel.sh ${{ env.VERSION }}
+          
+          EXPECTED_ZIPLINE_WHEEL="zipline_ai-${{ env.VERSION }}-py3-none-any.whl"
+          if [ ! -f "$EXPECTED_ZIPLINE_WHEEL" ]; then
+            echo "$EXPECTED_ZIPLINE_WHEEL not found"
+            exit 1
+          fi
+          echo "wheel_file=$EXPECTED_ZIPLINE_WHEEL" >> $GITHUB_OUTPUT
+
+      - name: Upload Wheel
+        uses: actions/upload-artifact@v4
+        with:
+          name: zipline-ai-wheel
+          path: ${{ steps.build-wheel.outputs.wheel_file }}
 
       - name: Build Bazel Project
         id: bazel-build
@@ -71,123 +106,280 @@ jobs:
           bazel build //service:service_assembly_deploy.jar \
             --remote_cache=https://storage.googleapis.com/zipline-bazel-cache \
             --google_credentials=bazel-cache-key.json
-          mkdir -p build_output
-          cp bazel-bin/spark/spark_assembly_deploy.jar build_output/
-          cp bazel-bin/cloud_aws/cloud_aws_lib_deploy.jar build_output/
-          cp bazel-bin/cloud_gcp/cloud_gcp_lib_deploy.jar build_output/
-          cp bazel-bin/service/service_assembly_deploy.jar build_output/
 
 
-      - name: Build AWS Quickstart Image
-        id: build-aws-app
-        shell: bash
-        env:
-          USER: root
-          SPARK_SUBMIT_PATH: spark-submit
-          PYTHONPATH: /srv/chronon
-          SPARK_VERSION: 3.1.1
-          JOB_MODE: local[*]
-          PARALLELISM: 2
-          EXECUTOR_MEMORY: 2G
-          EXECUTOR_CORES: 4
-          DRIVER_MEMORY: 1G
-          CHRONON_LOG_TABLE: default.chronon_log_table
-          CHRONON_ONLINE_CLASS: ai.chronon.integrations.aws.AwsApiImpl
-          AWS_DEFAULT_REGION: ${{env.AWS_REGION}}
-          DYNAMO_ENDPOINT: https://dynamodb.${{env.AWS_REGION}}.amazonaws.com
-          JAVA_OPTS: "-Xms1g -Xmx1g"
-          CLOUD_AWS_JAR: /app/cli/cloud_aws.jar
-        run:
-          docker build . -f "./Dockerfile" -t "aws-quickstart-image:latest"
+      - name: Upload Spark Assembly Jar
+        uses: actions/upload-artifact@v4
+        with:
+          name: spark-assembly-jar
+          path: bazel-bin/spark/spark_assembly_deploy.jar
 
-      - name: Build GCP Quickstart Image
-        id: build-gcp-app
-        shell: bash
-        env:
-          USER: root
-          SPARK_SUBMIT_PATH: spark-submit
-          PYTHONPATH: /srv/chronon
-          SPARK_VERSION: 3.1.1
-          JOB_MODE: local[*]
-          PARALLELISM: 2
-          EXECUTOR_MEMORY: 2G
-          EXECUTOR_CORES: 4
-          DRIVER_MEMORY: 1G
-          CHRONON_LOG_TABLE: default.chronon_log_table
-          CHRONON_ONLINE_CLASS: ai.chronon.integrations.cloud_gcp.GcpApiImpl
-          GCP_DEFAULT_REGION: ${{env.GCP_REGION}}
-          BIGTABLE_ENDPOINT: https://${{env.GCP_REGION}}-bigtable.googleapis.com
-          JAVA_OPTS: "-Xms1g -Xmx1g"
-          CLOUD_GCP_JAR: /app/cli/cloud_gcp.jar
-        run:
-          docker build . -f "./Dockerfile" -t "gcp-quickstart-image:latest"
+      - name: Upload Cloud AWS Jar
+        uses: actions/upload-artifact@v4
+        with:
+          name: cloud-aws-jar
+          path: bazel-bin/cloud_aws/cloud_aws_lib_deploy.jar
+
+      - name: Upload Cloud GCP Jar
+        uses: actions/upload-artifact@v4
+        with:
+          name: cloud-gcp-jar
+          path: bazel-bin/cloud_gcp/cloud_gcp_lib_deploy.jar
+
+      - name: Upload Service Assembly Jar
+        uses: actions/upload-artifact@v4
+        with:
+          name: service-assembly-jar
+          path: bazel-bin/service/service_assembly_deploy.jar
+    outputs:
+      wheel_file: ${{ steps.build-wheel.outputs.wheel_file }}
+
+
+  push_to_aws:
+    needs: build_artifacts
+    runs-on: ubuntu-latest
+
+    permissions:
+      id-token: write
+
+    steps:
+
+      - name: Download Python Wheel
+        uses: actions/download-artifact@v4
+        with:
+          name: zipline-ai-wheel
+
+      - name: Download Spark Assembly Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: spark-assembly-jar
+
+      - name: Download Cloud AWS Lib Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: cloud-aws-jar
+
+      - name: Download Service Assembly Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: service-assembly-jar
 
       - name: Configure AWS Credentials
         uses: aws-actions/configure-aws-credentials@v4
         with:
-          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/github-canary-updater
+          role-to-assume: arn:aws:iam::${{env.AWS_ACCOUNT_ID}}:role/github_actions
           aws-region: ${{env.AWS_REGION}}
 
-
-      - name: Login to Amazon ECR
-        id: login-ecr
-        uses: aws-actions/amazon-ecr-login@v2
-        with:
-          registries: ${{env.AWS_ACCOUNT_ID}}
-
-      - name: Tag, and push quickstart image to Amazon ECR
-        env:
-          ECR_REPOSITORY: ${{steps.login-ecr.outputs.registry}}/${{env.AWS_QUICKSTART_REPOSITORY}}
-          IMAGE_TAG: main
+      - name: Push Jars to s3 Bucket
         shell: bash
         run: |
           set -eo pipefail
-          docker tag "aws-quickstart-image:latest" "${{env.ECR_REPOSITORY}}:$IMAGE_TAG"
-          docker push "${{env.ECR_REPOSITORY}}:$IMAGE_TAG" || {
-            echo "Failed to push canary tag"
-            exit 1
-          }
-          docker tag "${{env.ECR_REPOSITORY}}:$IMAGE_TAG" "${{env.ECR_REPOSITORY}}:${{github.sha}}"
-          docker push "${{env.ECR_REPOSITORY}}:${{github.sha}}" || {
-            echo "Failed to push sha tag"
-            exit 1
-          }
-          echo "IMAGE $IMAGE_TAG is pushed to ${{env.ECR_REPOSITORY}}"
-          echo "image_tag=$IMAGE_TAG" 
-          echo "full_image=${{env.ECR_REPOSITORY}}:$IMAGE_TAG"
+          aws s3 cp ${{ needs.build_artifacts.outputs.wheel_file }} s3://zipline-artifacts-canary/release/candidate/wheels/ --metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          aws s3 cp spark_assembly_deploy.jar s3://zipline-artifacts-canary/release/candidate/jars/spark_assembly_deploy.jar --metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          aws s3 cp cloud_aws_lib_deploy.jar s3://zipline-artifacts-canary/release/candidate/jars/cloud_aws_lib_deploy.jar --metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          aws s3 cp service_assembly_deploy.jar s3://zipline-artifacts-canary/release/candidate/jars/service_assembly_deploy.jar --metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+
+
+  push_to_gcp:
+    needs: build_artifacts
+    runs-on: ubuntu-latest
+
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up QEMU
+        uses: docker/setup-qemu-action@v3
+
+      - name: Download Python Wheel
+        uses: actions/download-artifact@v4
+        with:
+          name: zipline-ai-wheel
+
+      - name: Download Spark Assembly Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: spark-assembly-jar
+
+      - name: Download Cloud GCP Lib Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: cloud-gcp-jar
+
+      - name: Download Service Assembly Jar
+        uses: actions/download-artifact@v4
+        with:
+          name: service-assembly-jar
+
 
       - name: Configure GCP Credentials
         uses: google-github-actions/auth@v2
         with:
           project_id: ${{env.GCP_PROJECT_ID}}
-          workload_identity_provider: projects/703996152583/locations/global/workloadIdentityPools/github-actions/providers/github
-          service_account: githubactions@canary-443022.iam.gserviceaccount.com
+          workload_identity_provider: projects/${{secrets.GCP_CANARY_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-actions/providers/github
+          service_account: github-actions@${{secrets.GCP_CANARY_PROJECT_ID}}.iam.gserviceaccount.com
 
       - name: Set up Google Cloud SDK
         uses: google-github-actions/setup-gcloud@v2
 
-      - name: Google Cloud Docker Auth
-        shell: bash
-        run: |-
-          gcloud auth configure-docker ${{env.GCP_REGION}}-docker.pkg.dev --quiet
-
-      - name: Push Quickstart to Artifact Registry
+      - name: Push Jars to GCS Bucket
         shell: bash
         env:
           GAR_QUICKSTART_REPOSITORY: ${{env.GCP_REGION}}-docker.pkg.dev/${{env.GCP_PROJECT_ID}}/canary-images/quickstart
           IMAGE_TAG: main
         run: |
           set -eo pipefail
-          docker tag "gcp-quickstart-image:latest" "${{env.GAR_QUICKSTART_REPOSITORY}}:$IMAGE_TAG"
-          docker push "${{env.GAR_QUICKSTART_REPOSITORY}}:$IMAGE_TAG" || {
-            echo "Failed to push canary tag"
-            exit 1
-          }
-          docker tag "${{env.GAR_QUICKSTART_REPOSITORY}}:$IMAGE_TAG" "${{env.GAR_QUICKSTART_REPOSITORY}}:${{github.sha}}"
-          docker push "${{env.GAR_QUICKSTART_REPOSITORY}}:${{github.sha}}" || {
-            echo "Failed to push sha tag"
-            exit 1
-          }
-          echo "IMAGE $IMAGE_TAG is pushed to ${{env.GAR_QUICKSTART_REPOSITORY}}"
-          echo "image_tag=$IMAGE_TAG" 
-          echo "full_image=${{env.GAR_QUICKSTART_REPOSITORY}}:$IMAGE_TAG"
+          gcloud storage cp ${{ needs.build_artifacts.outputs.wheel_file }} gs://zipline-artifacts-canary/release/candidate/wheels/
+          gcloud storage objects update gs://zipline-artifacts-canary/release/candidate/wheels/${{ needs.build_artifacts.outputs.wheel_file }} --custom-metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          gcloud storage cp spark_assembly_deploy.jar gs://zipline-artifacts-canary/release/candidate/jars/spark_assembly_deploy.jar
+          gcloud storage objects update gs://zipline-artifacts-canary/release/candidate/jars/spark_assembly_deploy.jar --custom-metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          gcloud storage cp cloud_gcp_lib_deploy.jar gs://zipline-artifacts-canary/release/candidate/jars/cloud_gcp_lib_deploy.jar
+          gcloud storage objects update gs://zipline-artifacts-canary/release/candidate/jars/cloud_gcp_lib_deploy.jar --custom-metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+          gcloud storage cp service_assembly_deploy.jar gs://zipline-artifacts-canary/release/candidate/jars/service_assembly_deploy.jar
+          gcloud storage objects update gs://zipline-artifacts-canary/release/candidate/jars/service_assembly_deploy.jar --custom-metadata="updated_date=$(date),commit=$(git rev-parse HEAD),branch=$(git rev-parse --abbrev-ref HEAD)"
+
+
+  run_aws_integration_tests:
+    runs-on: ubuntu-latest
+    needs: [ build_artifacts, push_to_aws ]
+
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Configure AWS Credentials for Canary Project
+        uses: aws-actions/configure-aws-credentials@v4
+        with:
+          role-to-assume: arn:aws:iam::${{secrets.AWS_ACCOUNT_ID}}:role/github_actions
+          aws-region: ${{secrets.AWS_REGION}}
+
+
+      # TODO Test 'run' commands when they are ready
+      - name: Run Quickstart Integration Tests
+        id: aws_integration_tests
+        shell: bash
+        run: |
+          set -xo pipefail
+          ./scripts/distribution/run_aws_quickstart.sh --canary          
+
+
+  run_gcp_integration_tests:
+    runs-on: ubuntu-latest
+    needs: [build_artifacts, push_to_gcp]
+
+    permissions:
+      id-token: write
+      contents: read
+
+    steps:
+      # Checkout the canary-confs repo with the branch with Zipline specific team.json
+      - name: Checkout repo
+        uses: actions/checkout@v4
+
+      - name: Configure GCP Credentials for Canary Project
+        uses: google-github-actions/auth@v2
+        with:
+          project_id: ${{secrets.GCP_CANARY_PROJECT_ID}}
+          workload_identity_provider: projects/${{secrets.GCP_CANARY_PROJECT_NUMBER}}/locations/global/workloadIdentityPools/github-actions/providers/github
+          service_account: github-actions@${{secrets.GCP_CANARY_PROJECT_ID}}.iam.gserviceaccount.com
+
+      - name: Set up Google Cloud SDK
+        uses: google-github-actions/setup-gcloud@v2
+
+      - name: Run Quickstart Integration Tests
+        shell: bash
+        id: gcp_integration_tests
+        run: |
+          set -xo pipefail
+          ./scripts/distribution/run_gcp_quickstart.sh --canary
+
+
+  clean_up_artifacts:
+    permissions:
+      contents: read
+
+    runs-on: ubuntu-latest
+
+    needs: [ run_aws_integration_tests, run_gcp_integration_tests ]
+
+    steps:
+      - name: Delete Artifacts
+        uses: geekyeggo/delete-artifact@v5
+        with:
+          name: |
+            zipline-ai-wheel
+            spark-assembly-jar
+            cloud-aws-jar
+            cloud-gcp-jar
+            service-assembly-jar
+
+
+  merge_to_main-passing-tests:
+    needs: [run_aws_integration_tests, run_gcp_integration_tests]
+    if: ${{ needs.run_aws_integration_tests.result == 'success' && needs.run_gcp_integration_tests.result == 'success' }}
+    runs-on: ubuntu-latest
+
+    permissions:
+      contents: write
+
+    steps:
+      - name: Checkout Main Branch
+        uses: actions/checkout@v4
+        with:
+          ref: main
+          fetch-depth: 0
+      - name: Update Stable Branch
+        env:
+          TARGET_BRANCH: main-passing-tests
+        run: |
+          echo "Merging to main branch after successful push to canary"
+          if git show-ref --quiet refs/heads/$TARGET_BRANCH; then
+            echo "Target branch $TARGET_BRANCH exists. Merging main into it..."
+            git checkout $TARGET_BRANCH
+            git merge main --no-ff -m "Merge main into $TARGET_BRANCH"
+          else
+            echo "Target branch $TARGET_BRANCH does not exist. Creating it..."
+            git checkout -b $TARGET_BRANCH main
+          fi
+          git push origin $TARGET_BRANCH
+
+      - name: Create CI Status File
+        run: |
+          echo ${{ github.sha }} > ci_success.txt
+
+      - name: Update CI Artifact
+        uses: actions/upload-artifact@v4
+        with:
+          name: ci_success
+          path: ci_success.txt
+
+
+  on_fail_notify_slack:
+    needs: [run_aws_integration_tests, run_gcp_integration_tests]
+    if: failure()
+    runs-on: ubuntu-latest
+
+    steps:
+      - name: Send Failure Notification
+        uses: slackapi/slack-github-action@v1
+        env:
+          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
+        with:
+          payload: |
+            {
+              "text": "Zipline CI Tests Failed\n\n The integration tests failed for commit ${{ github.sha }}. Please check the logs for more details.",
+              "attachments": [
+                {
+                  "text": "",
+                  "color": "#ff0000"
+                }
+              ]
+            }
